keboola/php-db-import-export

- composer.json
> KBC-58 Make package public on packagis

- composer.json
Align version of keboola/php-csv-db-import (5.x) with connection
> Sync version of keboola/php-csv-db-import with connection

- src/Backend/Snowflake/Exporter.php
- src/ExportOptions.php
- src/Storage/ABS/SnowflakeExportAdapter.php
- src/Storage/Snowflake/SelectSource.php
- src/Storage/Snowflake/Table.php
- src/Storage/SqlSourceInterface.php
- tests/functional/Snowflake/ExportTest.php
- tests/unit/ExportOptionsTest.php
- tests/unit/SourceStorage/ABS/SnowflakeExportAdapterTest.php
- tests/unit/SourceStorage/Snowflake/SelectSourceTest.php
- tests/unit/SourceStorage/Snowflake/TableTest.php
- new class for exporting from database using sql query
- remove sql query option from ExportOptions
> KBC-50 - new SelectSource snowflake source

- .travis.yml
- README.md
- composer.json
- src/Backend/BackendExportAdapterInterface.php
- src/Backend/BackendHelper.php
- src/Backend/ExporterInterface.php
- src/Backend/Snowflake/Exporter.php
- src/Backend/Snowflake/SnowflakeExportAdapterInterface.php
- src/Backend/Synapse/Exporter.php
- src/Backend/Synapse/SynapseExportAdapterInterface.php
- src/ExportOptions.php
- src/Storage/ABS/BaseFile.php
- src/Storage/ABS/DestinationFile.php
- src/Storage/ABS/SnowflakeExportAdapter.php
- src/Storage/ABS/SynapseExportAdapter.php
- src/Storage/DestinationInterface.php
- src/Storage/Snowflake/Table.php
- src/Storage/Synapse/SelectSource.php
- src/Storage/Synapse/Table.php
- tests/ABSSourceTrait.php
- tests/functional/ImportExportBaseTest.php
- tests/functional/Snowflake/ExportTest.php
- tests/functional/Synapse/ExportTest.php
- tests/functional/Synapse/SynapseBaseTestCase.php
- tests/unit/SourceStorage/ABS/DestinationFileTest.php
- tests/unit/SourceStorage/ABS/SnowflakeExportAdapterTest.php
- tests/unit/SourceStorage/ABS/SourceFileTest.php
- tests/unit/SourceStorage/ABS/SynapseExportAdapterTest.php
- tests/unit/SourceStorage/Snowflake/TableTest.php
- tests/unit/SourceStorage/Synapse/TableTest.php
jira: https://keboola.atlassian.net/browse/KBC-168
Implementace exportu ze Synapse do ABS prostřednitvím polybase.
- `ExporterInterface` pro Synapse `Keboola\Db\ImportExport\Backend\Synapse\Exporter`
- `BackendExportAdapterInterface` přes polybase `Keboola\Db\ImportExport\Storage\ABS\SynapseExportAdapter`
- `ABS\BaseFile` má novou metodu `getPolyBaseUrl`
- `ABS\DestinationFile` přímá v konstruktoru navíc `$blobMasterKey` který používá polybase
> KBC-168 synapse export

- src/Backend/Synapse/Importer.php
- src/Backend/Synapse/SqlCommandBuilder.php
- tests/functional/Synapse/SqlCommandBuilderTest.php
Vyhodil sem vytvoření tabulky z dedupu, takže to teď može zas jet celé v transakci.
> [Synapse] Run dedup in transaction

- .travis.yml
- composer.json
- phpunit.xml.dist
- src/Backend/Synapse/Importer.php
- src/Backend/Synapse/SqlCommandBuilder.php
- src/Backend/Synapse/SynapseImportOptions.php
- src/Storage/ABS/SourceFile.php
- tests/AbsLoader.php
- tests/functional/Synapse/ExportTest.php
- tests/functional/Synapse/FullImportTest.php
- tests/functional/Synapse/IncrementalImportTest.php
- tests/functional/Synapse/OtherImportTest.php
- tests/functional/Synapse/SqlCommandBuilderTest.php
- tests/functional/Synapse/SynapseBaseTestCase.php
- tests/unit/Backend/Synapse/ImporterTest.php
SLACK: https://keboola.slack.com/archives/C011BERCEBG/p1604078605035600?thread_ts=1603963295.000400&cid=C011BERCEBG
Synapse temp table type can be changed in synapse import options
> Synapse import options real table

- src/Backend/ImportState.php
- src/Backend/Synapse/Importer.php
JIRA https://keboola.atlassian.net/browse/KBC-1123
> KBC-1123 allow overwrite staging table name, so we save one insert into

- src/Backend/Synapse/Importer.php
- src/Backend/Synapse/SqlCommandBuilder.php
- tests/functional/Synapse/SqlCommandBuilderTest.php
JIRA: https://keboola.atlassian.net/browse/KBC-1250
Nakonec sem vyřadil je CAST a nechal Coalesce, při vyřazení coalesce padá test a je to na složitější zkoumání.
> KBC-1250 skip casting on synapse imports

- composer.json
- phpstan-baseline.neon
- phpstan.neon
- src/Storage/ABS/SourceDirectory.php
- src/Storage/ABS/SourceFile.php
- src/Storage/ABS/SynapseImportAdapter.php
- src/Storage/FileNotFoundException.php
- src/Storage/ManifestNotFoundException.php
- tests/data/tw_accounts.crlf.csv
- tests/functional/Synapse/FullImportTest.php
- tests/unit/Storage/ABS/SourceDirectoryTest.php
- tests/unit/Storage/ABS/SourceFileTest.php
- tests/unit/Storage/ABS/SynapseImportAdapterTest.php
Udělal sem jen update a vygeneroval baseline.
> update phpstan to 0.12

- composer.json
při každém updatu lib sa musí teď změnit constraint i tady.
> use constraint for keboola libs higher or equal

- composer.json
- src/Backend/Synapse/Importer.php
- src/Backend/Synapse/SqlCommandBuilder.php
- src/Backend/Synapse/SynapseException.php
- src/Backend/Synapse/ToStage/ToStageImporter.php
- src/Storage/ABS/SynapseImportAdapter.php
- src/Storage/Synapse/SynapseImportAdapter.php
- tests/data/typed_table.invalid-types.csv
- tests/functional/Synapse/OtherImportTest.php
- tests/functional/Synapse/SqlCommandBuilderTest.php
- tests/functional/SynapseNext/OtherImports/StageImportTest.php
- tests/unit/Backend/Synapse/SynapseExceptionTest.php
- tests/unit/Backend/Synapse/ToStage/FromABSCopyIntoAdapterTest.php
- tests/unit/Backend/Synapse/ToStage/FromTableInsertIntoAdapterTest.php
- tests/unit/Storage/ABS/SynapseImportAdapterTest.php
- tests/unit/Storage/Synapse/SynapseAdapterTest.php
JIRA: 
- https://keboola.atlassian.net/browse/KBC-1174
- https://keboola.atlassian.net/browse/KBC-1279
- https://keboola.atlassian.net/browse/KBC-1545
> KBC-1174 catch Bulk load exceptions and throw own exception

- azure-pipelines.yml
Přihol sem log, ještě budu v dalším PR testovat exitval.
> add paralell job log

- src/Backend/Exasol/ToStage/FromS3CopyIntoAdapter.php
- src/Backend/Exasol/ToStage/StageTableDefinitionFactory.php
- src/Backend/Exasol/ToStage/ToStageImporter.php
- src/Storage/S3/SnowflakeImportAdapter.php
- src/Storage/S3/SourceFile.php
- tests/functional/Exasol/ExasolBaseTestCase.php
- tests/functional/Exasol/StageImportS3Test.php
- tests/functional/Exasol/StageImportTest.php
S3 load to staging table - single CSV, Directory and Manifest
> Load to Exasol staging table from S3

- src/Backend/Exasol/ToStage/FromS3CopyIntoAdapter.php
- src/Backend/Exasol/ToStage/StageTableDefinitionFactory.php
- src/Backend/Exasol/ToStage/ToStageImporter.php
- src/Storage/S3/SnowflakeImportAdapter.php
- src/Storage/S3/SourceFile.php
- tests/functional/Exasol/ExasolBaseTestCase.php
- tests/functional/Exasol/StageImportS3Test.php
- tests/functional/Exasol/StageImportTest.php
New PR of implementation S3 in Exasol because https://github.com/keboola/php-db-import-export/pull/63 had a feature branch as the target one instead of master... :facepalm:
> S3 support in Exasol

- src/Backend/Exasol/ToFinalTable/FullImporter.php
- src/Backend/Exasol/ToFinalTable/IncrementalImporter.php
Jira: https://keboola.atlassian.net/browse/KBC-1786
> KBC-1786 Remove dedup table in finally

- src/Backend/Synapse/ToFinalTable/SqlBuilder.php
- tests/functional/SynapseNext/SqlBuilderTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1829
Toto by malo byt cajk tak davam na review, robil som este upravu na connection tak tu este tagnem https://github.com/keboola/connection/pull/3392
> index from source table

- src/Backend/Exasol/ToFinalTable/SqlBuilder.php
- tests/functional/Exasol/SqlBuilderTest.php
Use buildDefinitionString from phpdatatypes 
jira: https://keboola.atlassian.net/browse/KBC-1844
php-datatypes https://github.com/keboola/php-datatypes/pull/45
test in SAPI https://github.com/keboola/storage-api-php-client/pull/690
> KBC-1844 use definition string from phpdatatypes

- src/Backend/Synapse/ToFinalTable/SqlBuilder.php
- src/Backend/Synapse/ToStage/StageTableDefinitionFactory.php
- tests/functional/SynapseNext/SqlBuilderTest.php
- tests/unit/Backend/Synapse/ToStage/StageTableDefinitionFactoryTest.php
https://keboola.slack.com/archives/CFVRE56UA/p1638809468159200
Jira : https://keboola.atlassian.net/browse/KBC-2288
> fix replicate stage table

- src/Backend/Synapse/ToFinalTable/SqlBuilder.php
- tests/functional/SynapseNext/SqlBuilderTest.php
https://keboola.slack.com/archives/CFVRE56UA/p1638868818167600?thread_ts=1638809468.159200&cid=CFVRE56UA
> case insensitive search for columns in synapse import

- src/Backend/Teradata/ToStage/FromS3TPTAdapter.php
> fix TPT S3ConfigDir

- Dockerfile
Jira: https://keboola.atlassian.net/browse/KBC-2617
> Use s3 to download exasol driver

- phpstan-baseline.neon
- src/Backend/Synapse/ToFinalTable/SqlBuilder.php
- tests/functional/Synapse/SqlBuilderTest.php
https://keboola.atlassian.net/browse/KBC-2595?focusedCommentId=42003
> Synapse remove pk's from where conditions

- .github/workflows/tests.yml
- Dockerfile
- docker/exasol/createDeleteServer.sh
- tests/Common/StubLoader/AbsLoader.php
- tests/Common/StubLoader/BaseStubLoader.php
- tests/Common/StubLoader/S3Loader.php
- nastavuje exasol driver vo verzii EXASOL_ODBC-7.1.10.tar.gz by mala byt spravna verzia https://github.com/keboola/php-table-backend-utils/commit/b12c1aa1e2fba75e91cb239f6d005e58564bd8b1
- zapina a pauzuje vytvoreny exa server namiesto vytvarania vzdy noveho
- oprava v kode kde exa testom chybal file na s3
> fix exa driver version

- phpstan-baseline.neon
- src/Backend/Teradata/ToStage/Exception/FailedTPTLoadException.php
- src/Backend/Teradata/ToStage/Exception/NoMoreRoomInTDException.php
- src/Backend/Teradata/ToStage/FromS3TPTAdapter.php
- src/Storage/S3/TeradataExportTPTAdapter.php
- tests/functional/Teradata/StageImportTest.php
- tests/functional/Teradata/TeradataBaseTestCase.php
- uplne jsem se vykaslal na error tables, nejde z nich cist ani za zlaty tele a v te exception akorat zavazej.
- pri failu hledam string co signalizuje to, ze by mohlo dojit misto a kdyz tak vyhodim jinou exception
- upravil jsem testy, abych krok 2 mohl otestovat - do miniDB se snazim narvat megaTable
> KBC-2693 throw custom exception when "no more room" issue found

- composer.json
- src/Backend/Snowflake/ToFinalTable/IncrementalImporter.php
- src/Backend/Snowflake/ToStage/StageTableDefinitionFactory.php
- tests/functional/Snowflake/ToFinal/IncrementalImportTest.php
- tests/functional/Snowflake/ToFinal/SqlBuilderTest.php
Jira https://keboola.atlassian.net/browse/KBC-2758
depends on https://github.com/keboola/php-table-backend-utils/pull/70
incremental load for snflk
> KBC-2749 incremental load

- src/Backend/Helper/BackendHelper.php
- src/Backend/Snowflake/Importer.php
- src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
- src/Backend/Snowflake/ToStage/StageTableDefinitionFactory.php
- tests/functional/Snowflake/ToFinal/FullImportTest.php
put back generateTempTableName because of BC
> Put back generateTempTableName because of BC

- src/Backend/Snowflake/Exporter.php
- src/Storage/GCS/SnowflakeExportAdapter.php
- tests/unit/Storage/GCS/SnowflakeExportAdapterTest.php
implementacia exportu v I/E libke, potrebujem este doriesit nastavenie toho lifecyclu ale aj bez toho to funguje tak to dam zatial na predbezne review
> add snowflake export adapter

- src/Backend/Snowflake/ToFinalTable/FullImporter.php
> Dont drop staging table

- src/Backend/Exasol/ToFinalTable/FullImporter.php
- src/Backend/Teradata/ToFinalTable/FullImporter.php
based on INC_6455 - do not try to drop staging table. It is being done in connection/driver afterwards
> Dont drop staging table for exasol and TD

- src/Backend/Snowflake/ToFinalTable/FullImporter.php
- src/Backend/Snowflake/ToFinalTable/IncrementalImporter.php
- src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
- tests/functional/Snowflake/ToFinal/SqlBuilderTest.php
SLACK: https://keboola.slack.com/archives/C02BTQ5JADP/p1659525972397539
> Snowflake use truncate not delete

- src/Backend/Assert.php
- src/Backend/Snowflake/SnowflakeImportOptions.php
- src/Backend/Snowflake/ToStage/FromTableInsertIntoAdapter.php
- src/Exception/ColumnsMismatchException.php
- tests/functional/Snowflake/SnowflakeBaseTestCase.php
- tests/functional/Snowflake/ToStage/StageImportTest.php
- tests/unit/Backend/AssertTest.php
JIRA: https://keboola.atlassian.net/browse/KBC-2794
> KBC-2794 Allow require same tables on SNFLK backend

- phpunit.xml.dist
- src/Backend/Snowflake/Exporter.php
- src/Storage/S3/SnowflakeExportAdapter.php
- tests/unit/Storage/S3/SnowflakeExportAdapterTest.php
> add S3 SnowflakeExportAdapter

- src/Backend/Snowflake/SnowflakeException.php
- tests/functional/Backend/Snowflake/SnowflakeExceptionTest.php
- tests/functional/Snowflake/ToStage/StageImportFileTest.php
Jira: KBC-2862
Connection: https://github.com/keboola/connection/pull/3933
> KBC-2862 convert value conversion error to user error

- src/Backend/Exasol/ExasolException.php
- src/Storage/InvalidSourceDataException.php
- tests/unit/Backend/Exasol/ExasolExceptionTest.php
ZD#23528
jira: https://keboola.atlassian.net/browse/KBC-2776
> Convert error to user error

- src/Backend/Snowflake/ToFinalTable/IncrementalImporter.php
- src/Backend/Snowflake/ToFinalTable/SqlBuilder.php
- tests/functional/Snowflake/ToFinal/SqlBuilderTest.php
JIRA: https://keboola.atlassian.net/browse/KBC-2877
---
- pro typované tabulky při OM přestane dělat COALESCE
- vyhodil sem naše explicitní castování není to potřebe u SNFLK
> KBC-2877 skip coalesce if same tables are required

- src/Backend/Synapse/ToFinalTable/IncrementalImporter.php
- src/Backend/Synapse/ToStage/StageTableDefinitionFactory.php
- tests/unit/Backend/Synapse/ToStage/StageTableDefinitionFactoryTest.php
Jira: https://keboola.atlassian.net/browse/KBC-2870
> KBC-2870 - Synapse use dedup heap table on CI

- phpstan-baseline.neon
- src/Backend/Exasol/ToFinalTable/SqlBuilder.php
- src/Backend/Synapse/ToFinalTable/SqlBuilder.php
- src/Backend/Synapse/ToStage/StageTableDefinitionFactory.php
- src/Utils/StringCaseSensitivity.php
- tests/functional/Synapse/SqlBuilderTest.php
- tests/unit/Backend/Synapse/ToStage/StageTableDefinitionFactoryTest.php
- tests/unit/Utils/StringCaseSensitivityTest.php
JIRA: https://keboola.atlassian.net/browse/KBC-2903
> KBC-2903 Synapse columns comparison case insensitive

- .env.dist
- src/Backend/Teradata/ToFinalTable/FullImporter.php
- src/Backend/Teradata/ToFinalTable/SqlBuilder.php
- src/Backend/Teradata/ToStage/StageTableDefinitionFactory.php
- tests/functional/Snowflake/ToFinal/FullImportTest.php
- tests/functional/Teradata/FullImportTest.php
- tests/functional/Teradata/SqlBuilderTest.php
- tests/functional/Teradata/TeradataBaseTestCase.php
Jira: TER-64
---
zatim jen pro FullLoad
> TER-64 TD dedup for fullload

- .env.dist
- src/Backend/Bigquery/BigqueryImportOptions.php
- src/Backend/Bigquery/ToStage/FromTableInsertIntoAdapter.php
- src/Backend/Bigquery/ToStage/ToStageImporter.php
- src/Storage/Bigquery/SelectSource.php
- src/Storage/Bigquery/Table.php
- src/Storage/Exasol/SelectSource.php
- src/Storage/Exasol/Table.php
- src/Storage/Snowflake/SelectSource.php
- src/Storage/Snowflake/Table.php
- src/Storage/SqlSourceInterface.php
- src/Storage/Synapse/SelectSource.php
- src/Storage/Synapse/Table.php
- src/Storage/Teradata/SelectSource.php
- src/Storage/Teradata/Table.php
- tests/functional/Bigquery/BigqueryBaseTestCase.php
- tests/functional/Bigquery/FullImportTest.php
- tests/functional/DebugLogger.php
- tests/functional/Exasol/ExasolBaseTestCase.php
- tests/functional/ImportExportBaseTest.php
- tests/functional/Snowflake/SnowflakeBaseTestCase.php
- tests/functional/Synapse/SynapseBaseTestCase.php
- tests/functional/Teradata/TeradataBaseTestCase.php
- tests/unit/Storage/Bigquery/SelectSourceTest.php
- tests/unit/Storage/Bigquery/TableTest.php
- tests/unit/Storage/Snowflake/SelectSourceTest.php
- tests/unit/Storage/Snowflake/TableTest.php
- tests/unit/Storage/Synapse/SelectSourceTest.php
- tests/unit/Storage/Synapse/TableTest.php
> BIG-50 table import

- composer.json
- phpstan-baseline.neon
- src/Backend/Bigquery/BigqueryImportOptions.php
- src/Backend/Bigquery/ToFinalTable/IncrementalImporter.php
- src/Backend/Bigquery/ToFinalTable/SqlBuilder.php
- src/Backend/Bigquery/ToStage/FromTableInsertIntoAdapter.php
- src/Backend/Snowflake/SnowflakeImportOptions.php
- src/Backend/Synapse/SynapseImportOptions.php
- src/ImportOptions.php
- src/ImportOptionsInterface.php
- tests/Common/GCSSourceTrait.php
- tests/Common/StorageTrait.php
- tests/data/expectation.tw_accounts.increment.nodedup.csv
- tests/functional/Bigquery/BigqueryBaseTestCase.php
- tests/functional/Bigquery/FullImportTest.php
- tests/functional/Bigquery/ToFinal/IncrementalImportTest.php
- tests/functional/CsvStub.php
- tests/functional/DebugLogger.php
- tests/functional/ImportExportBaseTest.php
- tests/functional/Snowflake/SnowflakeBaseTestCase.php
- tests/functional/Snowflake/ToFinal/FullImportTest.php
- tests/functional/Snowflake/ToFinal/IncrementalImportTest.php
- tests/functional/Snowflake/ToStage/StageImportFileTest.php
- tests/functional/Storage/GCS/SourceFileTest.php
> BIG-53 Incremental load no dedup

- phpstan-baseline.neon
- src/Backend/Bigquery/ToFinalTable/FullImporter.php
- src/Backend/Bigquery/ToFinalTable/IncrementalImporter.php
- src/Backend/Bigquery/ToFinalTable/SqlBuilder.php
- tests/functional/Bigquery/BigqueryBaseTestCase.php
- tests/functional/Bigquery/SqlBuildTest.php
- tests/functional/Bigquery/ToFinal/FullImportTest.php
- tests/functional/Bigquery/ToFinal/IncrementalImportTest.php
- tests/functional/DebugLogger.php
Vsimol som si ze niektore generatory zacinaju na slovo test ked si pustim v PHPstorme testy nad celou triedou tak on to potom vyhodnoti ze je to test a spadne to na tom ze v tom nic neasertujeme :)
> Roman fix generator name

- phpstan-baseline.neon
- src/Backend/Bigquery/ToFinalTable/FullImporter.php
- src/Backend/Bigquery/ToFinalTable/IncrementalImporter.php
- src/Backend/Bigquery/ToFinalTable/SqlBuilder.php
- tests/functional/Bigquery/BigqueryBaseTestCase.php
- tests/functional/Bigquery/SqlBuildTest.php
- tests/functional/Bigquery/ToFinal/FullImportTest.php
- tests/functional/Bigquery/ToFinal/IncrementalImportTest.php
- tests/functional/DebugLogger.php
> BIG-58 Bigquery dedup

- src/Backend/Teradata/ToFinalTable/SqlBuilder.php
- tests/data/multi-pk.increment.csv
- tests/functional/Snowflake/IncrementalImportTest.php
- tests/functional/Snowflake/ToFinal/IncrementalImportTest.php
- tests/functional/Synapse/IncrementalImportNoTypesTest.php
- tests/functional/Synapse/IncrementalImportWithTypesTest.php
- tests/functional/Teradata/ToFinal/IncrementalImportTest.php
- tests/functional/Teradata/ToFinal/SqlBuilderTest.php
- tests/unit/Backend/Snowflake/ToStage/FromABSCopyIntoAdapterTest.php
- tests/unit/Backend/Snowflake/ToStage/FromGCSCopyIntoAdapterTest.php
- tests/unit/Backend/Snowflake/ToStage/FromS3CopyIntoAdapterTest.php
- tests/unit/Backend/Snowflake/ToStage/FromTableInsertIntoAdapterTest.php
> TER-71 add test for inc load with null

- src/Backend/Teradata/TeradataImportOptions.php
- src/Backend/Teradata/ToFinalTable/SqlBuilder.php
- src/ImportOptions.php
- tests/functional/Teradata/TeradataBaseTestCase.php
- tests/functional/Teradata/ToFinal/FullImportTest.php
- tests/functional/Teradata/ToFinal/IncrementalImportTest.php
- tests/functional/Teradata/ToFinal/SqlBuilderTest.php
Jira: TER-79
---
Connection: https://github.com/keboola/connection/pull/4099
IE https://github.com/keboola/php-db-import-export/pull/160
Driver https://github.com/keboola/php-storage-driver-teradata/pull/46
Common driver https://github.com/keboola/php-storage-driver-common/pull/19
> TER-79 Add usingTypes options

- src/Backend/Teradata/ToStage/FromTableInsertIntoAdapter.php
- tests/functional/Teradata/ToStage/StageImportTest.php
Jira: TER-82
check columns when it is typed table
---
> TER-82 assert column types on typed tables

- src/Backend/Bigquery/Export/GcsExportAdapter.php
> BIG-93 BQ add export query bindings

- src/Backend/Teradata/ToStage/FromABSTPTAdapter.php
Jira: TER-94
---
podobny problem jako u https://github.com/keboola/php-db-import-export/pull/169
> Fix abs load when no dir

- composer.json
> stable keboola/php-csv-db-import 6
